apiVersion: v1
kind: ConfigMap
metadata:
  name: gwtemplate-config
  namespace: __K8S_NAMESPACE_GDC__
data:
  NODE_ENV: "__NODE_ENV__"
  SECURITY_MODE: "__SECURITY_MODE__"
  NETWORK_MODE: "__NETWORK_MODE__"
  FHIR_LEGACY: "__FHIR_LEGACY__"
  JSON_LEGACY: "__JSON_LEGACY__"
  DIDCOMM_PLAIN: "__DIDCOMM_PLAIN__"
  DEMO_ALLOW_INSECURE_BEARER: "__DEMO_ALLOW_INSECURE_BEARER__"
  DEV_SEED: "__DEV_SEED__"
  HOST_INTERNAL_IP: "0.0.0.0"
  HOST_INTERNAL_PORT: "3000"
  HOST_PUBLIC_URL: "__GDC_PUBLIC_URL__"
  HOST_EXTERNAL_DOMAIN: ""
  HOST_EXTERNAL_PORT: "80"
  SECTORS_ALLOWED: "__SECTORS_ALLOWED__"
  QUEUE_PROVIDER: "__QUEUE_PROVIDER__"
  DB_PROVIDER: "__DB_PROVIDER__"
  STORAGE_PROVIDER: "__STORAGE_PROVIDER__"
  FIRESTORE_PROJECT_ID: "__GCP_PROJECT_ID__"
  GCS_BUCKET_NAME: "__GCS_BUCKET_NAME__"
  LOG_PROVIDER: "__LOG_PROVIDER__"
  REPLAY_PROTECTION_PROVIDER: "__REPLAY_PROTECTION_PROVIDER__"
  EMAIL_NOTIFICATION_PROVIDER: "__EMAIL_NOTIFICATION_PROVIDER__"
  CLEARING_HOUSE_MODE: "__CLEARING_HOUSE_MODE__"
  ICA_MODE: "__ICA_MODE__"
  ICA_URL_EXTERNAL: "__DATASPACE_ICA_EXTERNAL_URL__"
  HOST_LEGAL_NAME: "__HOST_LEGAL_NAME__"
  HOST_JURISDICTION: "__HOST_JURISDICTION__"
  HOST_ID_TYPE: "__HOST_ID_TYPE__"
  HOST_ID_VALUE: "__HOST_ID_VALUE__"
  HOST_ADMIN_EMAIL: "__HOST_ADMIN_EMAIL__"
  HOST_ADMIN_UID: "__HOST_ADMIN_UID__"
  HOST_ADMIN_ROLE: "__HOST_ADMIN_ROLE__"
  HOST_TERMS_URL: "__HOST_TERMS_URL__"
