apiVersion: v1
kind: Namespace
metadata:
  name: __K8S_NAMESPACE_GDC__
  labels:
    app.kubernetes.io/name: gwtemplate
    app.kubernetes.io/part-of: globaldatacare
    app.kubernetes.io/component: gateway
