apiVersion: v1
kind: Service
metadata:
  name: gwtemplate
  namespace: __K8S_NAMESPACE_GDC__
  labels:
    app.kubernetes.io/name: gwtemplate
  annotations:
    cloud.google.com/l4-rbs: "enabled"
    networking.gke.io/load-balancer-ip-addresses: "__GDC_STATIC_IP_NAME__"
spec:
  selector:
    app.kubernetes.io/name: gwtemplate
  ports:
    - name: http
      port: 80
      targetPort: http
  type: LoadBalancer
