import { resolveStorageScope } from '../../../config/storage-layout';
import type { LedgerChannelBinding } from '../../../services/ledger-channel-binding';
import { parseExpectedChannelBindings } from '../../../services/ledger-channel-binding';

export type FabricChannelPolicy = ReadonlySet<string>;

export function assertLedgerGenesisVerificationMode(input: Readonly<{
  deploymentEnv: string;
  networkMode: string;
  enabled: boolean;
}>): void {
  if (!input.enabled && (input.deploymentEnv === 'prod' || input.networkMode === 'network')) {
    throw new Error('prod/network scoped-v2 requires LEDGER_GENESIS_VERIFICATION=true.');
  }
}

/**
 * Builds the host's technical channel ceiling from the genesis bindings
 * generated by Fabric provisioning. Chaincode access is intentionally not
 * restricted per host in the MVP; GW business authorization and Fabric
 * policies still authorize each operation.
 */
export function fabricChannelPolicyFromBindings(
  bindings: readonly LedgerChannelBinding[],
): FabricChannelPolicy {
  return new Set(bindings.map(({ channel }) => channel));
}

export function resolveConfiguredFabricChannelPolicy(): FabricChannelPolicy | undefined {
  if (resolveStorageScope().layout !== 'scoped-v2') return undefined;
  if (String(process.env.LEDGER_GENESIS_VERIFICATION || '').trim().toLowerCase() !== 'true') {
    return undefined;
  }
  return fabricChannelPolicyFromBindings(
    parseExpectedChannelBindings(process.env.LEDGER_CHANNEL_GENESIS_SHA256),
  );
}

export function assertFabricChannelAllowed(
  channel: string,
  policy = resolveConfiguredFabricChannelPolicy(),
): void {
  if (policy && !policy.has(channel)) throw new Error(`Fabric channel is not allowed: ${channel}.`);
}

/**
 * Compatibility boundary for contract callers. The chaincode parameter is not
 * a host allowlist in the MVP; operation authorization belongs to GW licenses,
 * actor policy and the Fabric channel/chaincode policies themselves.
 */
export function assertFabricTargetAllowed(
  channel: string,
  _chaincode: string,
  policy = resolveConfiguredFabricChannelPolicy(),
): void {
  assertFabricChannelAllowed(channel, policy);
}
