apiVersion: v1
kind: Pod
metadata:
  name: fabric-tools
spec:
  restartPolicy: Never
  containers:
    - name: fabric-tools
      image: ghcr.io/hyperledger/fabric-tools:3.1.3
      imagePullPolicy: Always
      command: ["sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: configtx
          mountPath: /configtx
        - name: orderer-tls-cert
          mountPath: /certs
        - name: msp
          mountPath: /msp
        - name: admin
          mountPath: /admin
  volumes:
    - name: configtx
      configMap:
        name: configtx
    - name: orderer-tls-cert
      configMap:
        name: orderer-tls-cert
    - name: msp
      emptyDir: {}
    - name: admin
      emptyDir: {}
