apiVersion: v1
kind: Secret
metadata:
  name: orderer-msp
  namespace: test-fabric-v3
type: Opaque
data:
  # base64-encoded MSP contents (replace)
  # config.yaml: ""
  # signcerts/cert.pem: ""
  # keystore/key.pem: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: orderer-tls
  namespace: test-fabric-v3
type: Opaque
data:
  # ca.crt: ""
  # server.crt: ""
  # server.key: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: peer-msp
  namespace: test-fabric-v3
type: Opaque
data:
  # config.yaml: ""
  # signcerts/cert.pem: ""
  # keystore/key.pem: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: peer-tls
  namespace: test-fabric-v3
type: Opaque
data:
  # ca.crt: ""
  # server.crt: ""
  # server.key: ""
