apiVersion: v1
kind: ConfigMap
metadata:
  name: gwtemplate-config
  namespace: __K8S_NAMESPACE_GDC__
data:
  NODE_ENV: "demo"
  LOCAL_SERVICE_ROLE: "HOST,ICA,CA"
  SECURITY_MODE: "demo"
  NETWORK_MODE: "test"
  FHIR_LEGACY: "true"
  JSON_LEGACY: "true"
  DEMO_ALLOW_INSECURE_BEARER: "true"
  DEV_SEED: "true"
  MAINSECTOR: "health"
  SUBSECTORSALLOWED: "research,care,index"
  HOST_INTERNAL_IP: "0.0.0.0"
  HOST_INTERNAL_PORT: "3000"
  HOST_EXTERNAL_DOMAIN: "__HOST_EXTERNAL_DOMAIN__"
  HOST_EXTERNAL_PORT: "443"
  HOST_LEGAL_NAME: "__HOST_LEGAL_NAME__"
  HOST_JURISDICTION: "__HOST_JURISDICTION__"
  HOST_ID_TYPE: "__HOST_ID_TYPE__"
  HOST_ID_VALUE: "__HOST_ID_VALUE__"
  HOST_ADMIN_EMAIL: "__HOST_ADMIN_EMAIL__"
  HOST_ADMIN_UID: "__HOST_ADMIN_UID__"
  HOST_ADMIN_ROLE: "__HOST_ADMIN_ROLE__"
  HOST_TERMS_URL: "__HOST_TERMS_URL__"
  LOG_PROVIDER: "console"
  QUEUE_PROVIDER: "mem"
  DB_PROVIDER: "firestore"
  STORAGE_PROVIDER: "gcs"
  FIRESTORE_PROJECT_ID: "__GCP_PROJECT_ID__"
  GCS_BUCKET_NAME: "__GCS_BUCKET_NAME__"
  AUTH_TOKEN_VERIFIER: "demo"
