import { createHash, randomUUID } from 'crypto';
import type { RecordBase } from 'gdc-common-utils-ts/models/resource-document';
import type { IVaultRepository } from '../database/repositories/vault/vault.repository';
import { getEnvSectionId } from './section-env';

const DIGITAL_TWIN_SUBJECT_ALIAS_SECTION = 'digitaltwin_subject_aliases';
const RESEARCH_PROJECTION_AUTHOR = 'urn:gdc:research-projection';
const DIGITAL_TWIN_SUBJECT_URN_UUID = /^urn:uuid:[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

/**
 * Private derived search properties appended to the same projected resource record.
 * They are not a separate collection or public index, are never public FHIR claims,
 * and must be removed from search matches and materialized resources.
 */
export const DIGITAL_TWIN_SEARCH_TEXT_CLAIM = '__digitalTwinSearch.text';
export const DIGITAL_TWIN_SEARCH_DATE_CLAIM = '__digitalTwinSearch.date';
export const DIGITAL_TWIN_SEARCH_LANGUAGE_CLAIM = '__digitalTwinSearch.language';
export const DIGITAL_TWIN_SEARCH_CLAIM_PREFIX = '__digitalTwinSearch.';

export type DigitalTwinSubjectAlias = RecordBase & {
  type: 'digital-twin-subject-alias';
  sourceSubjectHash: string;
  twinSubjectId: string;
};

const BLOCKED_RESEARCH_CLAIM_SEGMENT = /(?:^|[.\-_])(display|text|title|description|note|instruction|name|address|telecom|contact|narrative)(?:$|[.\-_])/i;
const RESEARCH_IDENTIFIER_CLAIM = /(?:^|\.)(?:id|identifier)(?:\.value)?$/i;
const RESEARCH_PATIENT_CLAIM = /(?:^|\.)patient(?:\.reference)?$/i;
const RESEARCH_SUBJECT_CLAIM = /(?:^|\.)subject(?:\.reference)?$/i;

const RESEARCH_RESOURCE_TYPES = new Set([
  'MedicationStatement',
  'Observation',
  'AllergyIntolerance',
  'Condition',
  'DeviceUseStatement',
  'Flag',
  'Procedure',
  'ImagingStudy',
  'Immunization',
  'DiagnosticReport',
  'CarePlan',
  'Encounter',
  'AdverseEvent',
  'Composition',
]);

function sourceSubjectHash(sourceSubject: string): string {
  return createHash('sha256').update(String(sourceSubject || '').trim(), 'utf8').digest('hex');
}

function stableResearchUuid(seed: string): string {
  const bytes = createHash('sha256').update(seed, 'utf8').digest().subarray(0, 16);
  bytes[6] = (bytes[6] & 0x0f) | 0x50;
  bytes[8] = (bytes[8] & 0x3f) | 0x80;
  const hex = bytes.toString('hex');
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`;
}

/** Returns the private tenant section that binds operational subjects to research twins. */
export function getDigitalTwinSubjectAliasSectionId(): string {
  return getEnvSectionId(DIGITAL_TWIN_SUBJECT_ALIAS_SECTION);
}

/** Returns whether a subject is a standards-shaped, non-resolvable UUID URN. */
export function isDigitalTwinSubjectId(value: unknown): value is string {
  return DIGITAL_TWIN_SUBJECT_URN_UUID.test(String(value || '').trim());
}

/**
 * Confirms that a UUID URN was generated by this tenant's private alias
 * registry. Syntax alone is insufficient because a caller can invent a UUID.
 */
export async function isRegisteredDigitalTwinSubjectId(input: {
  vaultRepository: IVaultRepository;
  tenantVaultId: string;
  twinSubjectId: string;
}): Promise<boolean> {
  const twinSubjectId = String(input.twinSubjectId || '').trim();
  if (!isDigitalTwinSubjectId(twinSubjectId)) return false;
  const aliases = await input.vaultRepository.getContainersInSection<DigitalTwinSubjectAlias>(
    input.tenantVaultId,
    getDigitalTwinSubjectAliasSectionId(),
  );
  return aliases.some((alias) => alias?.twinSubjectId === twinSubjectId);
}

/**
 * Gets or creates the stable, non-resolvable research subject assigned to one
 * operational individual inside a tenant. The reversible binding remains in
 * the confidential tenant vault and is never copied into the research record.
 */
export async function getOrCreateDigitalTwinSubjectId(input: {
  vaultRepository: IVaultRepository;
  tenantVaultId: string;
  sourceSubject: string;
}): Promise<string> {
  const normalizedSource = String(input.sourceSubject || '').trim();
  if (!normalizedSource) throw new Error('sourceSubject is required');
  const id = sourceSubjectHash(normalizedSource);
  const sectionId = getDigitalTwinSubjectAliasSectionId();
  const existing = typeof input.vaultRepository.get === 'function'
    ? await input.vaultRepository.get<DigitalTwinSubjectAlias>(input.tenantVaultId, id, sectionId)
    : undefined;
  if (existing?.twinSubjectId && isDigitalTwinSubjectId(existing.twinSubjectId)) {
    return existing.twinSubjectId;
  }

  const twinSubjectId = `urn:uuid:${randomUUID()}`;
  await input.vaultRepository.put<DigitalTwinSubjectAlias>(input.tenantVaultId, [{
    id,
    type: 'digital-twin-subject-alias',
    sourceSubjectHash: id,
    twinSubjectId,
  }], sectionId);
  return twinSubjectId;
}

/** Returns whether a clinical resource is eligible for the minimal research projection. */
export function isDigitalTwinResearchResourceType(resourceType: string): boolean {
  return RESEARCH_RESOURCE_TYPES.has(String(resourceType || '').trim());
}

/**
 * Builds the fail-closed minimal research projection used before DataConv is
 * integrated. Free text and identifying claims are removed; resource and
 * business identifiers are replaced deterministically within the twin, and
 * every patient/subject reference is rebound to the research subject.
 *
 * The returned object also carries optional `__digitalTwinSearch.text`,
 * `.date` and `.language` properties on that same projected resource record.
 * Composition-wide discovery consumes them privately; they are not a separate
 * collection and never become clinical claims in a response.
 */
export function projectClaimsForDigitalTwin(input: {
  claims: Record<string, unknown>;
  resourceType: string;
  twinSubjectId: string;
}): Record<string, unknown> {
  const resourceType = String(input.resourceType || '').trim();
  const twinSubjectId = String(input.twinSubjectId || '').trim();
  if (!isDigitalTwinResearchResourceType(resourceType)) {
    throw new Error(`Resource type '${resourceType}' is not allowed in digital twin research projection.`);
  }
  if (!twinSubjectId) throw new Error('twinSubjectId is required');

  const searchableText = Array.from(new Set(Object.entries(input.claims || {})
    .filter(([key]) => /\.code-(?:display|text)$/i.test(String(key || '').trim()))
    .map(([, value]) => String(value || '').trim())
    .filter(Boolean)));
  const searchableDate = Object.entries(input.claims || {})
    .filter(([key]) => /\.(?:effective(?:-?datetime)?|issued|recorded(?:date|on)?|occurrence-?datetime|onset-?datetime|performed-?datetime|date|datetime|period-start)$/i.test(String(key || '').trim()))
    .map(([, value]) => String(value || '').trim())
    .find((value) => Boolean(value) && !Number.isNaN(Date.parse(value)));
  const searchableLanguage = Object.entries(input.claims || {})
    .find(([key]) => /\.language$/i.test(String(key || '').trim()))?.[1];

  const projected: Record<string, unknown> = {};
  for (const [key, rawValue] of Object.entries(input.claims || {})) {
    const normalizedKey = String(key || '').trim();
    if (!normalizedKey) continue;
    if (normalizedKey === '@context') {
      projected[normalizedKey] = rawValue;
      continue;
    }
    if (BLOCKED_RESEARCH_CLAIM_SEGMENT.test(normalizedKey)) continue;
    if (RESEARCH_PATIENT_CLAIM.test(normalizedKey)) continue;
    if (RESEARCH_SUBJECT_CLAIM.test(normalizedKey)) {
      projected[normalizedKey] = twinSubjectId;
      continue;
    }
    if (/\.author$/i.test(normalizedKey)) {
      projected[normalizedKey] = RESEARCH_PROJECTION_AUTHOR;
      continue;
    }
    if (RESEARCH_IDENTIFIER_CLAIM.test(normalizedKey)) {
      projected[normalizedKey] = `urn:uuid:${stableResearchUuid(`${twinSubjectId}|${resourceType}|${normalizedKey}|${String(rawValue || '')}`)}`;
      continue;
    }
    projected[normalizedKey] = rawValue;
  }
  if (searchableText.length > 0) projected[DIGITAL_TWIN_SEARCH_TEXT_CLAIM] = searchableText.join('\u001f');
  if (searchableDate) projected[DIGITAL_TWIN_SEARCH_DATE_CLAIM] = searchableDate;
  if (searchableLanguage) projected[DIGITAL_TWIN_SEARCH_LANGUAGE_CLAIM] = String(searchableLanguage).trim();
  return projected;
}
