// src/models/consent-rule.ts

export enum ClaimConsent {
    'decision' = 'Consent.decision',
    'action' = 'Consent.action',
    'category' = 'Consent.category',
    'subject' = 'Consent.subject',
    'actorIdentifier' = 'Consent.actor-identifier',
    'actorRole' = 'Consent.actor-role',
    'date' = 'Consent.date',
    'periodStart' = 'Consent.period-start',
    'periodEnd' = 'Consent.period-end',
    'grantee' = 'Consent.grantee',
    'verifiedBy' = 'Consent.verified-by',
    'verifiedDate' = 'Consent.verified-date',
    'purpose' = 'Consent.purpose',
    'identifier' = 'Consent.identifier',
    'attachmentContentType' = 'Consent.attachment-contentType',
    'attachmentData' = 'Consent.attachment-data',
    'attachmentId' = 'Consent.attachment-id',
}

/**
 * Defines the structured, query-optimized format for storing a single, atomic consent rule
 * in the vault (e.g., Firestore, CouchDB).
 *
 * This object is the "Query" model in a CQRS (Command Query Responsibility Segregation) pattern.
 * It is generated by the `ConsentManager` from the "Command" - a set of interoperable claims
 * provided in the `meta.claims` block of an incoming FHIR Consent resource.
 *
 * The backend's authorization engine queries against collections of these objects for high-speed
 * access decisions. The original FHIR Consent resource may be stored separately for auditing.
 *
 * All fields are derived from claims using the reverse-DNS format, e.g., the `decision` field
 * is populated from the `org.hl7.fhir.api.Consent.decision` claim.
 */
export interface ConsentRule {
    /**
     * JSON-LD context to define the vocabulary for the rule.
     * Value MUST be "org.hl7.fhir.api".
     */
    '@context': 'org.hl7.fhir.api';

    /**
     * The decision of the rule: permit or deny.
     * Derived from the `org.hl7.fhir.api.Consent.decision` claim.
     */
    'Consent.decision': 'permit' | 'deny';

    /**
     * The data sections this rule applies to, as a comma-separated list of coded values.
     * Derived from the `org.hl7.fhir.api.Consent.action` claim.
     * Example claim: "LOINC|48765-2,SNOMED|12345"
     */
    'Consent.action': string;

    /**
     * The type of consent document, as a comma-serpareted list of coded values.
     * Used for classifying the consent itself (e.g., for release of information).
     * Derived from the `org.hl7.fhir.api.Consent.category` claim.
     * Example claim: "LOINC|59284-0,LOINC|57016-8"
     */
    'Consent.category'?: string;

    /**
     * The subject of the consent.
     * Derived from the `org.hl7.fhir.api.Consent.patient.identifier` claim.
     */
    'Consent.subject': string;

    /**
     * The identifier of the actor (jurisdiction, organization, professional) this rule applies to.
     * This is the party whose access is being controlled.
     * Derived from a claim like `org.hl7.fhir.api.Consent.actor.reference.identifier`.
     * e.g., "urn:iso:3166-2:ES-CT", "did:web:hospital.example.com", "urn:email:dr-smith@example.com"
     */
    'Consent.actor-identifier': string;

    /**
     * The role of the actor this rule applies to.
     * Derived from a claim like `org.hl7.fhir.api.Consent.actor.role`.
     * e.g., "doctor", "nurse"
     */
    'Consent.actor-role': string;

    /**
     * The date the consent was granted (ISO 8601 Date).
     * Derived from the `org.hl7.fhir.api.Consent.date` claim.
     */
    'Consent.date': string;

    /**
     * Start of the consent's validity period (ISO 8601 DateTime).
     * Note: This is different from the date the consent was signed.
     * Derived from the start of the `org.hl7.fhir.api.Consent.period` claim.
     */
    'Consent.period-start'?: string;

    /**
     * End of the consent's validity period (ISO 8601 DateTime).
     * Derived from the end of the `org.hl7.fhir.api.Consent.period` claim.
     */
    'Consent.period-end'?: string;

    /**
     * The party to whom the consent is granted.
     * Derived from the `org.hl7.fhir.api.Consent.grantee` claim.
     */
    'Consent.grantee': string;

    /**
     * The DID of the entity (person or system) that verified the consent.
     * Derived from the `org.hl7.fhir.api.Consent.verified-by` claim.
     */
    'Consent.verified-by'?: string;

    /**
     * The date the consent was verified (ISO 8601 DateTime).
     * Derived from the `org.hl7.fhir.api.Consent.verified-date` claim.
     */
    'Consent.verified-date'?: string;


    /**
     * The purpose of use for this rule.
     * Derived from the `org.hl7.fhir.api.Consent.purpose` claim.
     * e.g., "ETREAT", "CAREMGT"
     */
    'Consent.purpose': string;

    /**
     * The original Consent resource ID for auditing.
     * Derived from the `org.hl7.fhir.api.Consent.identifier` claim.
     */
    'Consent.identifier': string;

    'Consent.attachment-contentType'?: string
    'Consent.attachment-data'?: string
    'Consent.attachment-id'?: string
}