// src/models/device-license.ts
// Copyright 2025 Antifraud Services Inc. under the Apache License, Version 2.0.

/**
 * A fingerprint of a specific device, used for binding a license to it.
 */
export interface DeviceInfo {
  /**
   * A stable, unique identifier for the specific app installation, generated by the client.
   * This is the primary key for device binding.
   */
  clientInstanceId: string;

  /** The operating system of the device (e.g., "iOS", "Android", "Windows"). */
  os?: string;

  /** The specific OS version. */
  osVersion?: string;

  /** The manufacturer of the device (e.g., "Apple", "Samsung"). */
  manufacturer?: string;
  
  /** The model of the device (e.g., "iPhone14,6"). */
  model?: string;
}

/**
 * A set of rules that a device must match to be eligible to activate a license.
 */
export interface DeviceRestrictions {
  /** A regex pattern for the allowed manufacturer(s). */
  manufacturer?: string;

  /** A regex pattern for the allowed model(s). */
  model?: string;
}

/**
 * Represents a single device activation license, enabling a user to register a specific device
 * for a tenant's service. It governs access based on user class, platform, and subscription terms.
 * Timestamps are stored as Unix epoch seconds (numeric).
 * All property names follow the camelCase convention.
 */
export interface DeviceLicense {
  /**
   * The unique identifier for this license document in the vault.
   */
  id: string;

  /**
   * The logical identifier of the tenant organization that owns this license.
   * @example "acme"
   */
  tenantId: string;
  
  /**
   * Identifier for the purchase order or invoice that generated this license.
   * All licenses created from the same purchase will share the same orderId.
   * @example "inv_12345"
   */
  orderId: string;

  /**
   * A secure, single-use code given to a user to activate a device.
   * This is generated when the license status becomes 'issued'.
   */
  activationCode?: string;

  /**
   * **CRITICAL:** Defines the class of user this license is intended for.
   * This allows for stratified licensing (e.g., selling "professional seats"
   * separately from "customer access").
   */
  userClass: 'employee' | 'customer';

  /**
   * **Specifies the functional category for an 'employee' license.**
   * This determines the set of roles the user is permitted to have.
   * This field MUST be present if userClass is 'employee'.
   * It is typically undefined for 'customer' licenses.
   * @example "medicalStaff", "firstResponder", "admin"
   */
  userCategory?: string;


  /**
   * Defines the platform this license is for.
   */
  type: 'mobile' | 'web';

  /**
   * The current lifecycle status of the license.
   * - 'available': Fresh license, ready to be assigned to a user.
   * - 'issued': Assigned to a user and an activation code has been generated.
   * - 'active': The user has successfully used the activation code to register a device.
   * - 'inactive': Deactivated by an administrator or user, or has expired.
   */
  status: 'available' | 'issued' | 'active' | 'inactive';

  /**
   * The subscription or purchase plan associated with this license.
   * @example "premium_annual" | "standard_monthly" | "trial"
   */
  plan: string;

  /**
   * Defines the renewal period for the license.
   * '1m' for one month, '12m' for one year.
   * A null value indicates the license does not auto-renew.
   */
  renewalCycle: '1m' | '12m' | null;
  
  /**
   * If true, the license can be reactivated after being made inactive
   * (e.g., after a user clicks "Log out everywhere"). If false, an inactive
   * license cannot be used again.
   */
  reactivationEnabled: boolean;

  /**
   * "Issued At" timestamp. The time the license was assigned to a user, as a Unix epoch in seconds.
   * Set when status moves to 'issued'.
   */
  issuedAt?: number;
  
  /**
   * "Activation Time" timestamp. The time the license was successfully used to register a device,
   * as a Unix epoch in seconds. Set when status moves to 'active'.
   */
  activatedAt?: number;

  /**
   * "Expiration Time" timestamp. The time at which the license and the device's authorization
   * expire, as a Unix epoch in seconds.
   */
  exp: number;

  /**
   * The unique identifier of the user (e.g., employeeId or customerId) to whom the license is issued.
   * Populated when the status becomes 'issued'.
   */
  subjectId?: string;
  
  /**
   * The unique identifier (`client_id`) of the device registered with this license.
   * Populated when the status becomes 'active'.
   */
  deviceId?: string;

  /**
   * Optional, pre-defined restrictions on which devices are allowed to activate this license.
   * Set at the time of license creation.
   */
  deviceRestrictions?: DeviceRestrictions;

  /**
   * A fingerprint of the device that successfully activated this license.
   * This is captured upon activation and is used to lock the license to that specific device.
   */
  deviceInfo?: DeviceInfo;
}
